//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Primordial Life.rc
//
#define ID_MAKE_DEFAULT                 3
#define ID_USE_DEFAULT                  4
#define IDD_ABOUTBOX                    100
#define ID_INITIAL_UPDATE               101
#define ID_GRAPH                        102
#define ID_DAY_COUNT                    103
#define IDS_POPULATION_COUNT            104
#define IDS_EXTINCTION_COUNT            105
#define IDS_NOTHING                     106
#define IDS_DAY_COUNT                   107
#define ID_POPULATION                   108
#define IDC_TERMINATE                   112
#define IDC_FEED                        121
#define IDD_NAG                         127
#define IDR_MAINFRAME                   128
#define IDR_PLIFETYPE                   129
#define IDR_ENVSTATS                    129
#define IDR_BIOTSTATS                   130
#define IDD_NETWORK                     132
#define IDD_STATUS                      134
#define IDI_TOP                         135
#define IDC_EDIT                        135
#define IDI_BOTTOM                      136
#define IDC_STATUS                      136
#define IDI_RIGHT                       137
#define IDD_NEW_SIMULATION              137
#define IDC_MAGNIFY                     137
#define IDI_LEFT                        138
#define IDD_EDITOR                      138
#define IDI_WORLD                       139
#define IDI_FEMALE                      140
#define IDI_MALE                        141
#define IDI_ASEXUAL                     142
#define IDI_ASEXUAL_FEMALE              143
#define IDR_EXPLORER_PALETTE            143
#define IDB_SPLASH                      144
#define IDB_SPLASH1                     145
#define IDR_MAGNIFY_MENU                149
#define IDC_RELOCATE                    150
#define IDC_SAVE                        151
#define IDC_LOAD                        152
#define IDC_CURE                        153
#define IDI_KEY                         157
#define IDD_CHANGE_PASSWORD             159
#define IDD_WORLD                       170
#define BIOT_OPTIONS                    172
#define HABITAT_OPTIONS                 173
#define IDB_BOTTOM                      174
#define IDB_TOP                         175
#define IDC_NEWPOPULATION               1000
#define IDC_OLDPOPULATION               1001
#define IDC_OLDSEED                     1002
#define IDC_WIDTH                       1003
#define IDC_HEIGHT                      1004
#define IDC_SEED                        1005
#define IDC_MUTE                        1006
#define IDC_WIDTH_TEXT                  1006
#define IDC_POPULATION                  1007
#define IDC_HEIGHT_TEXT                 1007
#define IDC_ENTIRE_SCREEN               1008
#define IDC_TEXT                        1009
#define IDC_ENTIRE_WINDOW               1009
#define IDC_ADDRESS                     1010
#define IDC_CUSTOM                      1010
#define IDC_LEFT_WORLD                  1011
#define IDC_FIT_WINDOW                  1011
#define IDC_RIGHT_WORLD                 1012
#define IDC_STARTING_POPULATION         1012
#define IDC_1_COLOR2                    1012
#define IDC_ERASE                       1013
#define IDC_TOP_WORLD                   1013
#define IDC_SPIN_POPULATION             1013
#define IDC_REGENTIME                   1014
#define IDC_BOTTOM_WORLD                1014
#define IDC_PROCESSING                  1014
#define IDC_NEWSEED                     1015
#define IDC_REGENCOST                   1017
#define IDC_TOTAL_DISTANCE              1017
#define IDC_GREEN                       1018
#define IDC_BENEFIT                     1018
#define IDC_LIFESPAN                    1019
#define IDC_RATIO                       1019
#define IDC_ABOUT                       1020
#define IDC_ENERGY                      1020
#define IDC_MUTATION                    1021
#define IDC_LINE1                       1021
#define IDC_ABOUT2                      1022
#define IDC_LINE2                       1022
#define IDC_FRICTION                    1023
#define IDC_MUTATION2                   1024
#define IDC_KEY                         1027
#define IDC_ENERGY_SLIDER               1027
#define IDC_ID                          1028
#define IDC_AGE_SLIDER                  1028
#define IDC_EDIT_KEY                    1029
#define IDC_SEX                         1029
#define IDC_EDIT_NAME                   1030
#define IDC_HOTKEY1                     1030
#define IDC_PARENTATTACK                1032
#define IDC_SIBLINGSATTACK              1033
#define IDC_EXPLORER                    1033
#define IDC_ASEXUAL                     1035
#define IDC_SEXUAL                      1036
#define IDC_BOTHSEXUAL                  1037
#define IDC_NOFLICKER                   1038
#define IDC_FULL_NAME                   1038
#define IDC_MOUSE                       1039
#define IDC_BUY                         1045
#define IDC_NETWORK                     1046
#define IDC_CONNECT_CHECK               1047
#define IDC_LISTEN_CHECK                1048
#define IDC_LEFT_ADDRESS                1050
#define IDC_RIGHT_ADDRESS               1051
#define IDC_TOP_ADDRESS                 1052
#define IDC_REGISTER_ONLINE             1052
#define IDC_BOTTOM_ADDRESS              1053
#define IDC_REGISTER_OFFLINE            1053
#define IDC_NEW_PASSWORD                1057
#define IDC_STATIC1                     1058
#define IDC_CONFIRM_PASSWORD            1058
#define IDC_NAME                        1063
#define IDC_WORLD_NAME                  1066
#define IDC_LEFT_ENABLE                 1067
#define IDC_RIGHT_ENABLE                1068
#define IDC_TOP_ENABLE                  1069
#define IDC_CHILDREN                    1069
#define IDC_BOTTOM_ENABLE               1070
#define IDC_FERTILE                     1070
#define IDC_APPLY                       1071
#define IDC_TIME                        1072
#define IDC_SPECIES                     1072
#define IDC_DIED                        1073
#define IDC_BORN                        1074
#define IDC_GENERATION                  1074
#define IDC_LEFT_EXCHANGED              1076
#define IDC_RIGHT_EXCHANGED             1077
#define IDC_FERTILE_TEXT                1077
#define IDC_TOP_EXCHANGED               1078
#define IDC_BOTTOM_EXCHANGED            1079
#define IDC_AGE                         1079
#define IDC_TYPES_PER_BIOT              1079
#define IDC_LEFT_BOUNCED                1080
#define IDC_ARMS_PER_BIOT               1080
#define IDC_RIGHT_BOUNCED               1081
#define IDC_SEGMENTS_PER_ARM            1081
#define IDC_TOP_BOUNCED                 1082
#define IDC_GENERATE                    1082
#define IDC_BOTTOM_BOUNCED              1083
#define IDC_COMBO1                      1083
#define IDC_VIEW_SERVERS                1084
#define OPW_TAB                         1085
#define DLG_SCRNSAVECONFIGURE           2003
#define DLG_ABOUTHELP1                  2004
#define DLG_SCRNSAVECONFIGURE1          2005
#define DLG_SIMULATION_SETTINGS         2006
#define IDD_BREEDING                    2007
#define IDD_INITIAL_POPULATION          2008
#define IDD_ENVIRONMENT                 2009
#define IDD_BIOTS                       2010
#define IDD_NET                         2011
#define ID_VIEW_FULLSCREEN              32771
#define ID_SIMULATION_WORLDSTATUS       32772
#define ID_BIOTS_FEED                   32773
#define ID_BIOTS_STATUS                 32774
#define ID_BIOTS_EDIT                   32775
#define ID_SIMULATION_STARTSIMULATION   32776
#define ID_SIMULATION_SETTINGS          32777
#define ID_HELP_REGISTER                32778
#define ID_HELP_HELP                    32779
#define ID_REGISTER                     32779
#define ID_BIOTS_TERMINATE              32780
#define ID_STEP_TIMER                   32781
#define ID_BIOTS_MAGNIFY                32782
#define ID_SHAPE                        32783
#define ID_COMPOSITION                  32784
#define ID_ENERGY                       32785
#define ID_BREEDING                     32786
#define ID_BIOTS_RELOCATE               32787
#define ID_BIOTS_SAVE                   32788
#define ID_BIOTS_LOAD                   32789
#define ID_BIOTS_CURE                   32790
#define ID_VIEW_BESTFITWINDOW           32797
#define ID_VIEW_BAR                     32798
#define ID_ENVIRONMENT_STATS            32804
#define ID_AGE_SPREAD                   32806
#define ID_LINE_TYPES                   32807
#define ID_ENERGY_SPREAD                32809
#define IDS_DAY                         61204
#define IDS_POPULATION                  61205
#define IDS_EXTINCTIONS                 61206
#define IDS_EMPTY                       61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
